services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file: .env
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./volumes/db/schema.sql:/docker-entrypoint-initdb.d/00-schema.sql
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend.dockerfile
    container_name: backend
    env_file: .env
    environment:
      - DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
      - ./storage_data:/usr/src/app/storage_data
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/frontend.dockerfile
    container_name: frontend
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - .:/usr/src/frontend
      - frontend_node_modules:/usr/src/frontend/node_modules
    depends_on:
      - backend

volumes:
  db_data:
  frontend_node_modules:
  backend_node_modules:
