name: Deploy

on:
  push:
    branches: [ "live" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: |
          $Utf8NoBom = New-Object System.Text.UTF8Encoding $False
          [System.IO.File]::WriteAllText(".env", "${{ secrets.PROD_ENV_FILE }}", $Utf8NoBom)

      - name: Build & Deploy
        run: docker compose up -d --build --remove-orphans

      - name: Cleanup
        run: docker image prune -f

# nginx

# events {}

# http {
#   server {
#     listen 80;

#     location / {
#       proxy_pass http://frontend:80;
#     }

#     location /trpc {
#       proxy_pass http://backend:8083/trpc;
#     }
#   }
# }